# Generated by Django 6.0.3 on 2026-04-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=10)),
                ('strategy', models.CharField(default='MovingAverageStrategy', max_length=50)),
                ('entry_price', models.FloatField()),
                ('sl', models.FloatField()),
                ('tp', models.FloatField()),
                ('quantity', models.FloatField()),
                ('fee_entry', models.FloatField(default=0.0)),
                ('slippage_in', models.FloatField(default=0.0)),
                ('order_id', models.CharField(max_length=100)),
                ('rsi_at_entry', models.FloatField(default=0.0)),
                ('risk_amount', models.FloatField(default=0.0)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('fee_exit', models.FloatField(default=0.0)),
                ('slippage_out', models.FloatField(default=0.0)),
                ('exit_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('gross_pnl', models.FloatField(blank=True, null=True)),
                ('net_pnl', models.FloatField(blank=True, null=True)),
                ('r_multiple', models.FloatField(blank=True, null=True)),
                ('holding_candles', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trade Record',
                'verbose_name_plural': 'Trade Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
