# Generated by Django 6.0.3 on 2026-08-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='traderecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('symbol',), name='unique_open_trade_per_symbol'),
        ),
    ]
