# Generated by Django 6.0.3 on 2026-08-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_traderecord_unique_open_trade_per_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='entry_narrative',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='exit_narrative',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='production_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='research_verdict',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='verdict_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
