# Generated by Django 6.0.3 on 2026-08-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_traderecord_entry_narrative_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='traderecord',
            name='unique_open_trade_per_symbol',
        ),
        migrations.AddField(
            model_name='traderecord',
            name='venue',
            field=models.CharField(blank=True, default='binance', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='traderecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('symbol', 'venue'), name='unique_open_trade_per_symbol'),
        ),
    ]
