# Generated by Django 6.0.3 on 2026-08-22 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_learningpath_course_enrollment_module_lesson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchExperiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hypothesis_text', models.TextField()),
                ('structured_spec', models.JSONField(blank=True, default=dict)),
                ('research_plan', models.JSONField(blank=True, default=dict)),
                ('tool_call_log', models.JSONField(blank=True, default=list)),
                ('statistical_results', models.JSONField(blank=True, default=dict)),
                ('validation_results', models.JSONField(blank=True, default=dict)),
                ('robustness_results', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('ai_interpretation', models.TextField(blank=True)),
                ('verdict', models.CharField(blank=True, choices=[('SUPPORTED', 'Supported'), ('PARTIALLY_SUPPORTED', 'Partially Supported'), ('INCONCLUSIVE', 'Inconclusive'), ('REJECTED', 'Rejected'), ('INVALID_RESEARCH', 'Invalid Research'), ('INSUFFICIENT_DATA', 'Insufficient Data'), ('REQUIRES_REVIEW', 'Requires Review'), ('REGIME_DEPENDENT', 'Regime Dependent'), ('SUPERSEDED_BY_EXISTING_RESEARCH', 'Superseded By Existing Research')], max_length=40)),
                ('random_seed', models.IntegerField(blank=True, null=True)),
                ('code_version', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PLANNED', 'Planned'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rerun_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reruns', to='bot.researchexperiment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_experiments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
