# Generated by Django 6.0.3 on 2026-08-27 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_researchexperiment_capability_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researchexperiment',
            name='data_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='HypothesisFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('feature_family', models.JSONField(default=list)),
                ('assets', models.JSONField(default=list)),
                ('venue', models.CharField(blank=True, max_length=40)),
                ('timeframe', models.CharField(blank=True, max_length=10)),
                ('horizons', models.JSONField(default=list)),
                ('correction_method', models.CharField(default='fdr_bh', max_length=40)),
                ('alpha', models.FloatField(default=0.05)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hypothesis_families', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='researchexperiment',
            name='hypothesis_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='bot.hypothesisfamily'),
        ),
    ]
