# Generated by Django 6.0.3 on 2026-09-02 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_researchexperiment_data_fingerprint_hypothesisfamily_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchexperiment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_experiments', to=settings.AUTH_USER_MODEL),
        ),
    ]
