# Generated by Django 6.0.3 on 2026-09-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_researchexperiment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='leg',
            field=models.CharField(blank=True, choices=[('A', 'Leg A'), ('B', 'Leg B')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='pair_trade_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
