# Generated by Django 6.0.3 on 2026-09-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_traderecord_leg_traderecord_pair_trade_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='cycle_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='dca_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
